Repository bcgov/onroutebc, pull requests merged in 2023-12, with the labels that each got.

#834 ci: workflow updates
  .github/workflows/.deploy.yml
  .github/workflows/analysis.yml
  .github/workflows/merge.yml
  .github/workflows/pr-close.yml
  .github/workflows/pr-open.yml
  charts/onroutebc/Chart.yaml
Labels: github_actions

#837 ci: fix github api call
  .github/workflows/merge.yml
Labels: bug

#846 ci: use action-get-pr
  .github/workflows/merge.yml
  .github/workflows/pr-open.yml
Labels: github_actions

#844 chore(deps): css-tools vulnerability
  frontend/package-lock.json
  frontend/package.json
Labels: dependencies

#847 ci: PR close/open interrupt, but not merge_groups
  .github/workflows/pr-open.yml
Labels: bug, github_actions

#945 ORV2-1765 Add @LogMethodExecution() to every service method
  dops/src/modules/auth/auth.service.ts
  dops/src/modules/common/cdogs.service.ts
  dops/src/modules/common/s3.service.ts
  dops/src/modules/dgen/dgen.service.ts
  dops/src/modules/dms/dms.service.ts
  vehicles/src/modules/auth/auth.service.ts
  vehicles/src/modules/common/common.service.ts
  vehicles/src/modules/common/dops.service.ts
  vehicles/src/modules/company-user-management/company/company.service.ts
  vehicles/src/modules/company-user-management/pending-idir-users/pending-idir-users.service.ts
  vehicles/src/modules/company-user-management/pending-users/pending-users.service.ts
  vehicles/src/modules/company-user-management/users/users.service.ts
  vehicles/src/modules/email/email.service.ts
  vehicles/src/modules/payment/payment-report.service.ts
  vehicles/src/modules/payment/payment.service.ts
  vehicles/src/modules/permit/application.service.ts
  vehicles/src/modules/permit/permit.service.ts
  vehicles/src/modules/vehicles/power-unit-types/power-unit-types.service.ts
  vehicles/src/modules/vehicles/power-units/power-units.service.ts
  vehicles/src/modules/vehicles/trailer-types/trailer-types.service.ts
  vehicles/src/modules/vehicles/trailers/trailers.service.ts
Labels: dont merge

#966 fix: ORV2-1808 More sonarcloud fixes
  frontend/src/common/components/header/Header.tsx
  frontend/src/common/helpers/util.ts
  frontend/src/features/idir/reporting/api/reports.ts
  frontend/src/features/permits/apiManager/permitsAPI.ts
  frontend/src/features/permits/helpers/sorter.ts
  frontend/src/features/permits/pages/TermOversize/components/pay/PermitPayFeeSummary.tsx
Labels: dont review, dont merge
