Repository bcgov/onroutebc, pull requests merged in 2024-01, with the labels that each got.

#1020 ci: only let MERGED PRs promote images
  .github/workflows/pr-close.yml
Labels: bug, github_actions

#1069 Orv2 1501: added endpoint for search company by company name or client id
  vehicles/src/modules/company-user-management/company/company.controller.ts
  vehicles/src/modules/company-user-management/company/company.service.ts
  vehicles/src/modules/company-user-management/company/dto/response/read-company-metadata.dto.ts
  vehicles/src/modules/company-user-management/company/entities/company.entity.ts
  vehicles/src/modules/permit/permit.service.ts
  vehicles/test/unit/company/company.controller.spec.ts
  vehicles/test/unit/company/company.service.spec.ts
  vehicles/test/util/mocks/data/company.mock.ts
Labels: dont review, dont merge

#1126 ORV2-1903 - Upgrading Frontend Packages
  frontend/.eslintrc.cjs
  frontend/package-lock.json
  frontend/package.json
  frontend/src/common/authentication/LoadBCeIDUserContext.tsx
  frontend/src/common/authentication/LoadBCeIDUserRolesByCompany.tsx
  frontend/src/common/authentication/LoadIDIRUserContext.tsx
  frontend/src/common/authentication/LoadIDIRUserRoles.tsx
  frontend/src/common/authentication/LoginRedirect.tsx
  frontend/src/common/components/form/CustomFormComponents.tsx
  frontend/src/common/components/form/subFormComponents/CustomOutlinedInput.tsx
  frontend/src/common/helpers/testHelper.tsx
  frontend/src/common/helpers/util.ts
  frontend/src/features/idir/reporting/api/reports.ts
  frontend/src/features/idir/reporting/api/users.ts
  frontend/src/features/idir/reporting/forms/PaymentAndRefundDetail.tsx
  frontend/src/features/idir/reporting/types/types.ts
  frontend/src/features/idir/search/components/IDIRCompanySearchResults.tsx
  frontend/src/features/idir/search/components/IDIRPermitSearchResults.tsx
  frontend/src/features/idir/search/table/CompanySearchResultColumnDef.tsx
  frontend/src/features/manageProfile/apiManager/hooks.ts
  frontend/src/features/manageProfile/components/dashboard/ManageProfilesDashboard.tsx
  frontend/src/features/manageProfile/components/forms/companyInfo/CompanyInfoForm.tsx
  frontend/src/features/manageProfile/components/forms/myInfo/MyInfoForm.tsx
  frontend/src/features/manageProfile/pages/EditUserDashboard.tsx
  frontend/src/features/manageProfile/pages/MyInfo.tsx
  frontend/src/features/manageProfile/pages/UserManagement.tsx
  frontend/src/features/manageProfile/types/manageProfile.d.ts
  frontend/src/features/manageVehicles/apiManager/hooks.ts
  frontend/src/features/manageVehicles/components/dashboard/EditVehicleDashboard.tsx
  frontend/src/features/manageVehicles/components/dashboard/ManageVehiclesDashboard.tsx
  frontend/src/features/manageVehicles/components/form/PowerUnitForm.tsx
  frontend/src/features/manageVehicles/components/form/tests/helpers/prepare.tsx
  frontend/src/features/manageVehicles/components/list/List.tsx
  frontend/src/features/permits/components/dashboard/ApplicationStepPage.tsx
  frontend/src/features/permits/components/dashboard/PermitLists.tsx
  frontend/src/features/permits/components/dashboard/tests/integration/fixtures/getVehicleInfo.ts
  frontend/src/features/permits/components/dashboard/tests/integration/helpers/prepare.tsx
  frontend/src/features/permits/components/form/tests/helpers/ApplicationDetails/prepare.tsx
  frontend/src/features/permits/components/list/List.tsx
  frontend/src/features/permits/components/permit-list/BasePermitList.tsx
  frontend/src/features/permits/hooks/hooks.ts
  frontend/src/features/permits/pages/Amend/AmendPermit.tsx
  frontend/src/features/permits/pages/TermOversize/tests/helpers/TermOversizeReview/prepare.tsx
  frontend/src/features/permits/pages/Void/FinishVoid.tsx
  frontend/src/features/permits/pages/Void/VoidPermit.tsx
  frontend/src/features/permits/pages/Void/components/VoidPermitForm.tsx
  frontend/src/features/permits/pages/Void/hooks/useVoidPermit.ts
  frontend/src/features/wizard/subcomponents/CompanyAndUserInfoSteps.tsx
  frontend/vite.config.ts
Labels: dont merge
