Repository bcgov/onroutebc, pull requests merged in 2025-04, with the labels that each got.

#1893 Orv2 3401 credit file
  scheduler/src/common/constants/garms.constant.ts
  scheduler/src/common/enum/permit-approval-source.enum.ts
  scheduler/src/common/helper/garms.helper.ts
  scheduler/src/modules/common/entities/company.entity.ts
  scheduler/src/modules/common/entities/credit-account.entity.ts
  scheduler/src/modules/common/entities/permit-data.entity.ts
  scheduler/src/modules/common/entities/permit.entity.ts
  scheduler/src/modules/garms/dto/garms-cash-details.dto.ts
  scheduler/src/modules/garms/dto/garms-credit-details.dto.ts
  scheduler/src/modules/garms/dto/garms-credit-header.dto.ts
  scheduler/src/modules/garms/garms.module.ts
  scheduler/src/modules/garms/garms.service.ts
  scheduler/src/modules/tps-permit/tps-permit.module.ts
  scheduler/src/modules/tps-permit/tps-permit.service.ts
Labels: dont review, dont merge

#1894 ORV2-3490 Basic BCeID Implementation
  dops/src/enum/idp.enum.ts
  dops/src/modules/auth/jwt.strategy.ts
  frontend/src/common/authentication/Authentication.tsx
  frontend/src/common/authentication/LoginRedirect.tsx
  frontend/src/common/authentication/OnRouteBCContext.tsx
  frontend/src/common/authentication/auth-walls/NewBCeIDAuthWall.tsx
  frontend/src/common/authentication/types.ts
  frontend/src/common/components/idpredirect/IDPRedirect.tsx
  frontend/src/common/pages/ClaimProfileUnauthorized.tsx
  frontend/src/common/types/idp.ts
  frontend/src/features/homePage/welcome/WelcomePage.tsx
  frontend/src/features/idir/company/IDIRCreateCompany.tsx
  frontend/src/features/idir/search/components/IDIRCompanySearchResults.tsx
  frontend/src/features/manageProfile/apiManager/hooks.ts
  frontend/src/features/wizard/components/dashboard/ChallengeProfileSteps.tsx
  frontend/src/features/wizard/components/dashboard/CreateProfileSteps.tsx
  frontend/src/features/wizard/hooks/hooks.ts
  frontend/src/features/wizard/subcomponents/CompanyAndUserInfoSteps.tsx
  frontend/src/routes/Routes.tsx
  frontend/src/routes/constants.ts
  policy/src/enum/idp.enum.ts
  policy/src/modules/auth/jwt.strategy.ts
  vehicles/src/common/enum/idp.enum.ts
  vehicles/src/modules/auth/jwt.strategy.ts
  vehicles/src/modules/company-user-management/company/company.service.ts
  vehicles/src/modules/company-user-management/company/dto/response/read-company-metadata.dto.ts
  vehicles/src/modules/company-user-management/company/dto/response/read-company.dto.ts
  vehicles/src/modules/company-user-management/users/dto/response/read-user-orbc-status.dto.ts
  vehicles/src/modules/company-user-management/users/users.service.ts
  vehicles/test/unit/users/users.service.spec.ts
  vehicles/test/util/mocks/data/company.mock.ts
  vehicles/test/util/mocks/data/user.mock.ts
Labels: dont review, dont merge

#1900 Orv2 3799 - Fix incorrect postal code validation behaviour
  frontend/src/features/manageProfile/components/forms/companyInfo/subForms/CompanyInfoGeneralForm.tsx
Labels: dont review

#1935 ORV2-2771 - Display info box only for non-finance staff user
  frontend/src/common/constants/constants.ts
  frontend/src/features/manageProfile/components/dashboard/ManageProfilesDashboard.tsx
  frontend/src/features/settings/components/dashboard/ManageSettingsDashboard.tsx
  frontend/src/features/settings/pages/CreditAccountMetadataComponent.tsx
  frontend/src/features/settings/pages/ViewCreditAccount.tsx
Labels: dont merge

#1966 ORV2-4031 BE: Interim GARMS/TPS Show Credit Account Information
  frontend/src/common/authentication/PermissionMatrix.ts
  frontend/src/common/constants/bannerMessages.ts
  frontend/src/features/settings/components/creditAccount/ActivityTable.tsx
  frontend/src/features/settings/components/creditAccount/StatusChip.scss
  frontend/src/features/settings/components/creditAccount/StatusChip.tsx
  frontend/src/features/settings/pages/CreditAccount.scss
  frontend/src/features/settings/pages/ViewCreditAccount.tsx
  frontend/src/features/settings/types/creditAccount.ts
  vehicles/src/modules/credit-account/credit-account.controller.ts
  vehicles/src/modules/credit-account/credit-account.service.ts
  vehicles/src/modules/credit-account/dto/request/update-credit-account-verification.dto.ts
  vehicles/src/modules/credit-account/dto/response/read-credit-account-limit.dto.ts
  vehicles/src/modules/credit-account/profiles/credit-account.profile.ts
Labels: dont review

#1992 ORV2-4145 - BE: Update: Enhance staff amend permit behaviour
  vehicles/src/modules/permit-application-payment/application/application.service.ts
  vehicles/src/modules/permit-application-payment/application/company-application.controller.ts
Labels: dont merge
